FROM node:18-alpine

WORKDIR /app
COPY server ./server
RUN apk add --no-cache docker-cli build-base g++
RUN cd server && npm install --legacy-peer-deps

EXPOSE 8080
CMD ["npm", "--prefix", "server", "start"]